use_frameworks!

platform :ios, '10.0'

target 'MangKit_Example' do
  pod 'MangKit', :path => '../'

  target 'MangKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
